{
  src
  {
        POLYTOPES/properties.mag
        POLYTOPES/standard.mag 
        POLYTOPES/classical.mag
        POLYTOPES/involutions.mag
        POLYTOPES/search.mag
        MGS/util.mag
        MGS/search.mag
  }
}
