174,0
S,IsSGGI,Test whether G is an SGGI on its given generator list,0,1,0,0,0,0,0,0,0,-27,,36,-38,-38,-38,-38,-38
S,IsSGGI,Test whether the group generated by L is an SGGI on these generators,0,1,0,0,0,0,0,0,0,82,,36,-38,-38,-38,-38,-38
S,IsSGGIModSubgroup,Test whether G/N is an SGGI,0,2,0,0,0,0,0,0,0,-27,,0,0,-27,,36,-38,-38,-38,-38,-38
S,IsSGGIModScalars,Test whether the matrix group G is an SGGI modulo its subgroup of scalar matrices,0,1,0,0,0,0,0,0,0,178,,36,-38,-38,-38,-38,-38
S,SchlafliSymbol,Compute the Schlafli symbol of the SGGI G,0,1,0,0,0,0,0,0,0,-27,,82,-38,-38,-38,-38,-38
S,SchlafliSymbol,Compute the Schlafli symbol of the SGGI generated by L,0,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,HasIntersectionProperty,"Test whether G, with its given generators, satisfies the intersection property",0,1,0,0,0,0,0,0,0,-27,,36,-38,-38,-38,-38,-38
S,HasIP,"Test whether G, with its given generators, satisfies the intersection property",0,1,0,0,0,0,0,0,0,-27,,36,-38,-38,-38,-38,-38
S,HasIntersectionPropertyModSubgroup,"Test whether G/N, with the given generators for G, satisfies the intersection condition",0,2,0,0,0,0,0,0,0,-27,,0,0,-27,,36,-38,-38,-38,-38,-38
S,HasIPModSubgroup,"Test whether G/N, with the given generators for G, satisfies the intersection condition",0,2,0,0,0,0,0,0,0,-27,,0,0,-27,,36,-38,-38,-38,-38,-38
S,IsStringCGroup,Test whether G is a string C-group on its given generator list,0,1,0,0,0,0,0,0,0,-27,,36,-38,-38,-38,-38,-38
S,IsStringCGroupModuloSubgroup,"Test whether G/N, with the given generator list for G, is a string C-group",0,2,0,0,0,0,0,0,0,-27,,0,0,-27,,36,-38,-38,-38,-38,-38
