174,0
T,SGGI,-,0
A,SGGI,6,AsGrp,IsIrred,SchlafliType,DistGens,Rank,HasIP
S,StringGroupGeneratedByInvolutions,Turn the group G generated by involutions into an sggi,0,1,0,0,0,0,0,0,0,224,,SGGI,-38,-38,-38,-38,-38
S,StringGroupGeneratedByInvolutions,Turn the group G generated by involutions into an sggi,0,1,0,0,0,0,0,0,0,178,,SGGI,-38,-38,-38,-38,-38
S,SchlafliType,Return the Schlafli type of the sggi H,0,1,0,0,0,0,0,0,0,SGGI,,82,-38,-38,-38,-38,-38
S,Generators,Return the distinguished generating sequence of the SGGI H,0,1,0,0,0,0,0,0,0,SGGI,,82,-38,-38,-38,-38,-38
S,Rank,Return the rank of sggi H,0,1,0,0,0,0,0,0,0,SGGI,,148,-38,-38,-38,-38,-38
S,HasIntersectionProperty,Test whether sggi H satisfies the intersection property,0,1,0,0,0,0,0,0,0,SGGI,,36,-38,-38,-38,-38,-38
S,IsStringCGroup,Test whether sggi H is a string C-group,0,1,0,0,0,0,0,0,0,SGGI,,36,-38,-38,-38,-38,-38
S,IsStringCGroup,Test whether G is a string C-group on its given generator list,0,1,0,0,0,0,0,0,0,-27,,36,-38,-38,-38,-38,-38
S,Print,Print H,0,1,0,0,1,0,0,0,0,SGGI,,-38,-38,-38,-38,-38,-38
S,eq,H eq J,0,2,0,0,0,0,0,0,0,SGGI,,0,0,SGGI,,36,-38,-38,-38,-38,-38
