174,0
T,SGGI,-,0
A,SGGI,6,AsGrp,IsIrred,SchlafliType,DistGens,Rank,HasIP
S,StringGroupGeneratedByInvolutions,Turn the group G generated by involutions into an SGGI,0,1,0,0,0,0,0,0,0,224,,SGGI,-38,-38,-38,-38,-38
S,StringGroupGeneratedByInvolutions,Turn the group G generated by involutions into an SGGI,0,1,0,0,0,0,0,0,0,178,,SGGI,-38,-38,-38,-38,-38
S,Dual,The dual of an SGGI,0,1,0,0,0,0,0,0,0,SGGI,,SGGI,-38,-38,-38,-38,-38
S,SchlafliType,Return the Schlafli type of the SGGI,0,1,0,0,0,0,0,0,0,SGGI,,82,-38,-38,-38,-38,-38
S,Generators,Return the distinguished generating sequence of the SGGI H,0,1,0,0,0,0,0,0,0,SGGI,,82,-38,-38,-38,-38,-38
S,Group,Return the group underlying the SGGI,0,1,0,0,0,0,0,0,0,SGGI,,-27,-38,-38,-38,-38,-38
S,Rank,Return the rank of the SGGI,0,1,0,0,0,0,0,0,0,SGGI,,148,-38,-38,-38,-38,-38
S,Print,Print SGGI,0,1,0,0,1,0,0,0,0,SGGI,,-38,-38,-38,-38,-38,-38
S,HasIntersectionProperty,Test whether SGGI satisfies the intersection property,0,1,0,0,0,0,0,0,0,SGGI,,36,-38,-38,-38,-38,-38
S,IsStringCGroup,Test whether SGGI is a string C-group,0,1,0,0,0,0,0,0,0,SGGI,,36,-38,-38,-38,-38,-38
S,IsStringCGroup,Test whether G is a string C-group on its given generator list,0,1,0,0,0,0,0,0,0,-27,,36,-38,-38,-38,-38,-38
S,eq,Basic equality test for SGGIs,0,2,0,0,0,0,0,0,0,SGGI,,0,0,SGGI,,36,-38,-38,-38,-38,-38
S,IsIsomorphic,Decide whether two SGGIs are isomorphic,0,2,0,0,0,0,0,0,0,SGGI,,0,0,SGGI,,36,141,-38,-38,-38,-38
S,IsEquivalent,Decide whether two SGGIs are equivalent up to isomorphism and duality,0,2,0,0,0,0,0,0,0,SGGI,,0,0,SGGI,,36,-38,-38,-38,-38,-38
S,IsInnerIsomorphic,Decide whether two SGGIs (have the same parent group and) are inner isomorphic,0,2,0,0,0,0,0,0,0,SGGI,,0,0,SGGI,,36,-28,-38,-38,-38,-38
